apiVersion: v1
kind: Pod
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  containers:
    - name: flask-api
      image: nghia5/flask-api:latest 
      ports:
        - containerPort: 5000
      resources:
        requests:
          cpu: "100m"
          memory: "50Mi"
        limits:
          cpu: "600m"
          memory: "100mi"