apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nghia5/flask-api:latest
    resources:
      limits:
        memory: "100Mi"
        cpu: "100m"
    ports:
      - containerPort: 5000
    env:
      - name: NAME
        valueFrom:
          configMapKeyRef:
            name: cmapp
            key: name
      - name: AGE
        valueFrom:
          configMapKeyRef:
            name: cmapp
            key: age



